### ISSUE TITLE
Problems loading stashes

### ISSUE THREAD

**Issue by Naruto2005BY** [Procurement-PoE/Procurement#1006]
After the last update sometimes (1/3 times) I get bugs with refreshing tabs, it just freezes and takes a minute to fail and just proceeds to the next tab without updating anything.

**Comment by thailyn** [comment]
Please provide some additional details.  Is this when you are logging in?  Refreshing all your tabs after logging in?  And by "last update" you mean 1.26.1 (released yesterday)?

Please also attach your `DebugInfo.log` file.

**Comment by Naruto2005BY** [comment]
[DebugInfo.log](https://github.com/Stickymaddness/Procurement/files/2997418/DebugInfo.log)
I press refresh all tabs or refresh used tabs in stash menu it happens, can't reproduce it now, works totally fine. Will record a video if it happens again

**Comment by thailyn** [comment]
I see in the log first a lot of issues with CloudFlare, until I presume you updated Procurement.  Then a bunch of fairly generic errors when trying to fetch tabs with the error message `Время ожидания операции истекло`, which I think means the operation timed out.  This might have been caused by an issue on GGG's end, where the requests to get the stash contents could not be completed in time.

If you experience the issue again, also check that the pathofexile.com website is working well.  If it isn't, then that usually means a problem with their backend, and that will affect Procurement, too.
